<?php
$lang = array(
    'logo' => 'Open Library Logo',
    'my_books' => 'My Books',
    'browse_all' => 'Browse All',
    'search_placeholder' => 'Search...',
    'hello_user' => 'Hello',
    'dashboard' => 'Dashboard',
    'log_out' => 'Log Out',
    'my_profile' => 'My Profile',
    'my_reading_stats' => 'My Reading Stats',
    'import_export' => 'Import & Export',
    'Return_Books' => 'Return Books',
    'Manage_Books' => 'Manage Books',
    'privacy_public' => 'Privacy: Public',
    'my_borrowed_books' => 'My Borrowed Books',
    'no_borrowed_books' => 'You haven\'t borrowed any books currently.',
    'home' => 'Home',
    'browse' => 'Browse',
    'hello_user_greeting' => 'Hello, user',
    'welcome_back' => 'Welcome back, user!',
    'dashboard_description' => 'This is your dashboard. Here you can see your borrowed books, recommendations, and account settings.',
    'borrowed_books_section' => 'Your Borrowed Books',
    'twisted_lies' => 'Twisted Lies',
    'borrowed_on' => 'Borrowed on: 2025-06-12 01:11:55',
    'status' => 'Status: Borrowed',
	
	// Manage books
  'manage_books_title' => 'Manage Books',
	'add_new_book' => 'Add New Book',
    'edit_book' => 'Edit Book',
    'update_book' => 'Update Book',
    'add_book' => 'Add Book',
    'cancel' => 'Cancel',
    'title' => 'Title',
    'author' => 'Author',
    'isbn' => 'ISBN',
    'isbn_placeholder' => 'e.g., 978-1234567890',
    'available_copies' => 'Available Copies',
    'copies' => 'Copies',
    'genre_category' => 'Genre/Category',
    'select_genre' => 'Select Genre...',
    'genre' => 'Genre',
    'cover_image' => 'Cover Image',
    'current_image' => 'Current image:',
    'current_cover' => 'Current cover',
    'readable_pdf' => 'Readable PDF File',
    'current_pdf' => 'Current PDF:',
    'view_current_pdf' => 'View Current PDF',
    'upload_new_file_to_replace' => 'Upload new file to replace',
    'description' => 'Description',
    'enter_book_description' => 'Enter book description...',
	 'cover' => 'Cover',
    'pdf' => 'PDF',
    'actions' => 'Actions',
	 'search_placeholder_manage' => 'Search by title, author, or ISBN...',
    'all_genres' => 'All Genres',
    'search' => 'Search',
    'clear' => 'Clear',
	 'please_fix_errors' => 'Please fix the following errors:',
	'no_image' => 'No Image',
    'out_of_stock' => 'Out of Stock',
    'left' => 'left',
    'view' => 'View',
    'edit' => 'Edit',
    'delete' => 'Delete',
    'confirm_delete' => 'Are you sure you want to delete',
    'no_books_found' => 'No books found',
    'start_adding_books' => 'Start by adding your first book to the library.',

    // Admin returns
    'admin_return_panel'       => 'Admin Return Panel',
    'delete_all_returned_records' => 'Delete all returned borrowed book records',
    'clear_returned_books'     => 'Clear Returned Books',
    'username'                 => 'Username',
    'book_title'               => 'Book Title',
    'borrowed_at'              => 'Borrowed At',
    'due_date'                 => 'Due Date',
    'returned_date'            => 'Returned Date',
    'late_fee'                 => 'Late Fee',
    'action'                   => 'Action',
    'mark_as_returned'         => 'Mark as Returned',
    'returned'                 => 'Returned',
    'no_borrowed_books_to_return' => 'No borrowed books to return.',

    // mybooks.php specific keys
    'currently_borrowed_books'   => 'Currently Borrowed Books',
    'previously_borrowed_books'  => 'Previously Borrowed Books',
    'due'                         => 'Due'
);
?>
