<?php
$lang = array(
    // index.php / books
    'available_books'          => 'Боломжтой номнууд',
    'borrow'                   => 'Зээлэх',
    'borrow_success'           => 'Ном амжилттай зээлэгдлээ!',
    'currently_borrowed_books' => 'Одоогоор зээлсэн номнууд',
    'due'                      => 'Эцсийн хугацаа',
    'error'                    => 'Алдаа',
    'fantasy'                  => 'Фантази', // or 'Уран сэтгэмж' if you prefer
    'manage_books'             => 'Ном удирдах',
    'previously_borrowed_books'=> 'Өмнө зээлсэн номнууд',
    'processing'               => 'Боловсруулж байна...',
    'request_failed'           => 'Хүсэлт амжилтгүй боллоо',
    'return_books'             => 'Ном буцаах',
    'romance'                  => 'Романс',
    'unavailable'              => 'Боломжгүй',

    // profile.php / user interface
    'avatar'                   => 'Профайл зураг',
    'change_avatar'            => 'Профайл зураг солих',
    'import_export'            => 'Импорт ба Экспорт',
    'my_reading_stats'         => 'Миний уншсан номны үзүүлэлт',
    'privacy_public'           => 'Нууцлал: Нийтийн',

    // statistics / charts
    'borrowed_books_by_genre'  => 'Зээлсэн ном жанраар',
    'average_rating_by_genre'  => 'Дундаж үнэлгээ жанраар',
    'average_rating'           => 'Дундаж үнэлгээ',

    // other
    'returned'                 => 'Буцаасан',
	 'welcome_message'         => 'Номын сангийн туслахад тавтай морилно уу!',
	 'help_text'         => 'Би танд ном зээлэх, номын сангийн ажиллах цаг, торгуулийн тухай болон номын сантай холбоотой бусад асуултад тусалж чадна.!',
	 'borrow_book'  => 'Энэ номыг зээлэх',
    'back_to_list' => 'Номын жагсаалт руу буцах',
    'read_online'  => 'Онлайнаар унших',
    'publisher'    => 'Хэвлэлийн газар',
	'pages' => 'Хуудас',
    'published'    => 'Хэвлэгдсэн он',
	
	// manage_books.php
	  'manage_books_title' => 'Номын удирдлага',
    'add_new_book' => 'Шинэ ном нэмэх',
    'edit_book' => 'Ном засах',
    'update_book' => 'Ном шинэчлэх',
    'add_book' => 'Ном нэмэх',
    'cancel' => 'Болих',
    'title' => 'Нэр',
    'author' => 'Зохиогч',
    'isbn' => 'ISBN',
    'isbn_placeholder' => 'Жишээ: 978-1234567890',
    'available_copies' => 'Бэлэн хуулбарууд',
    'copies' => 'Хуулбар',
    'genre_category' => 'Төрөл/Ангилал',
    'select_genre' => 'Төрөл сонго...',
    'genre' => 'Төрөл',
    'cover_image' => 'Давхар зураг',
    'current_image' => 'Одоогийн зураг:',
    'current_cover' => 'Одоогийн давхар зураг',
    'readable_pdf' => 'Уншиж болох PDF файл',
    'current_pdf' => 'Одоогийн PDF:',
    'view_current_pdf' => 'Одоогийн PDF харах',
    'upload_new_file_to_replace' => 'Шинэ файлыг солихын тулд байршуулна уу',
    'description' => 'Тайлбар',
    'enter_book_description' => 'Номын тайлбарыг оруулна уу...',
    'cover' => 'Давхар',
    'pdf' => 'PDF',
    'actions' => 'Үйлдлүүд',
    'search_placeholder_manage' => 'Нэр, зохиогч, эсвэл ISBN-аар хайх...',
    'all_genres' => 'Бүх төрлүүд',
    'search' => 'Хайх',
    'clear' => 'Цэвэрлэх',
    'please_fix_errors' => 'Дараах алдааг засна уу:',
    'no_image' => 'Зураггүй',
    'out_of_stock' => 'Хүртээмжгүй',
    'left' => 'үлдсэн',
    'view' => 'Харах',
    'edit' => 'Засах',
    'delete' => 'Устгах',
    'confirm_delete' => 'Та устгахыг хүсч байна уу',
    'no_books_found' => 'Ном олдсонгүй',
    'start_adding_books' => 'Сангадаа анхны номоо нэмэхээс эхлэе.',

    // header.php / navigation
    'all'                      => 'Бүгд',
    'author'                   => 'Зохиолч',
    'browse_all'               => 'Бүгдийг үзэх',
    'dashboard'                => 'Хяналтын самбар',
    'edit_avatar'              => 'Аватарыг засах',
    'hello_user'               => 'Сайн уу',
    'language'                 => 'Хэл',
    'log_in'                   => 'Нэвтрэх',
    'log_out'                  => 'Гарах',
    'logo'                     => 'Лого',
    'my_books'                 => 'Миний номнууд',
    'my_profile'               => 'Миний профайл',
    'search_placeholder'       => 'Хайх...',
    'sign_up'                  => 'Бүртгүүлэх',
    'subjects'                 => 'Сэдвүүд',
    'title'                    => 'Гарчиг',
    'trending'                 => 'Тренд',
	// admin_returns.php
	 'admin_return_panel'       => 'Админы буцаалтын самбар',
    'delete_all_returned_records' => 'Буцаасан бүх бичлэгийг устгах',
    'clear_returned_books'     => 'Буцаасан номнуудыг арилгах',
    'username'                 => 'Хэрэглэгчийн нэр',
    'book_title'               => 'Номын нэр',
    'borrowed_at'              => 'Зээлсэн огноо',
    'due_date'                 => 'Эцсийн хугацаа',
    'returned_date'            => 'Буцаасан огноо',
    'late_fee'                 => 'Хожимдуулалтын төлбөр',
    'action'                   => 'Үйлдэл',
    'mark_as_returned'         => 'Буцааснаар тэмдэглэх',
    'returned'                 => 'Буцаасан',
    'no_borrowed_books_to_return' => 'Буцаах ном алга.'
);
?>
